// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFU7DdIAiZfwGXL3rwsYCAThaSUog6N4',
    appId: '1:838079767924:web:19de6cf8514e34d992b821',
    messagingSenderId: '838079767924',
    projectId: 'dmsproject-99d8e',
    authDomain: 'dmsproject-99d8e.firebaseapp.com',
    storageBucket: 'dmsproject-99d8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4G1aX4OGLZh4RzDNiLUUY5yiFjRMeWSU',
    appId: '1:838079767924:android:3e703d3bdaf3bd2292b821',
    messagingSenderId: '838079767924',
    projectId: 'dmsproject-99d8e',
    storageBucket: 'dmsproject-99d8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFMDqiVmtzT5iL1scj3pvbaIwHTGRlOZ8',
    appId: '1:838079767924:ios:8121eb5c0107da2e92b821',
    messagingSenderId: '838079767924',
    projectId: 'dmsproject-99d8e',
    storageBucket: 'dmsproject-99d8e.appspot.com',
    androidClientId: '838079767924-0qhrukk6tstchurkqh6fuunek4cpt5gq.apps.googleusercontent.com',
    iosClientId: '838079767924-5q3hgepmsl1e278hlo3lcb3c50semdj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
